language: python
# Existing Python versions
python:
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
services:
  - xvfb
before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r src/requirements.txt
# command to run tests
script:
  - py.test --doctest-modules -v src/test_simulation_data.py
  - echo 'Current working directory - ' $(pwd) 
  - cd src
  - pyinstaller -i data/traffic.ico -F SimRunner.py
  - ls 
  - sed -i "s/datas=\[\]/datas=\[('\/home\/travis\/build\/HuyNVuong\/Traffic-Simulator\/src\/buttonImages\/*', 'buttonImages'),('\/home\/travis\/build\/HuyNVuong\/Traffic-Simulator\/data\/*', 'data')\]/" SimRunner.spec
  - pyinstaller SimRunner.spec

after_script:
  - mv dist/SimRunner.exe dist/Simulation.exe
  - sshpass -p "Vnh15111999" scp dis/Simulation.exe hvuong@cse.unl.edu:~/cse361/